export const LIMITS = {
  MAX_FOLDER_NAME_LENGTH: 80,
  MAX_SERVICE_NAME_LENGTH: 120,
  MAX_CREDENTIAL_FIELD_LENGTH: 500,
  MAX_CREDENTIAL_NOTES_LENGTH: 5000,
  MAX_NOTE_TITLE_LENGTH: 200,
  MAX_NOTE_CONTENT_LENGTH: 20000,
  MAX_TAG_LENGTH: 50,
  MAX_CUSTOM_FIELDS: 10,
  MAX_CUSTOM_FIELD_LABEL_LENGTH: 100,
  MAX_CUSTOM_FIELD_VALUE_LENGTH: 500,
};
